name: Build and Deploy Node Application to AWS EC2

on:
  push:
    branches: [ master, develop ]

jobs:
  live-deploy:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npx tsc

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip ./build/**/* appspec.yml deploy.sh
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://s3-fillkie-develop/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name fillkie
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name live
          --s3-location bucket=s3-fillkie-develop,bundleType=zip,key=$GITHUB_SHA.zip
